export const fullListStreetsByCity = {
  Tiranë: [
    'Rruga Ferit Xhajko',
    'Rruga Bardhyl',
    'Rruga 4 Dëshmorët',
    'Rruga e Dibrës',
    'Rruga e Barrikadave',
    'Rruga Kongresi i Manastirit',
    'Rruga e Durrësit',
    'Rruga e Kavajës',
    'Rruga Myslym Shyri',
    'Rruga Pjetër Budi',
    'Rruga Dritan Hoxha',
  ],
  Durrës: [
    'Rruga Vëllazërimi',
    'Rruga Glaukia',
    'Rruga Adria',
    'Rruga Shqipja Arbnore',
    'Rruga Pavarësia',
    'Rruga Bajram Tusha',
    'Rruga Azem Hajdari',
    'Rruga Mujo Ulqinaku',
    'Rruga Mbreti Pirro',
    'Rruga e Shqipeve',
    'Rruga Bajrma Curri',
  ],
  Korçë: [
    'Rruga Kristaq Prifti',
    'Rruga 28 Nëntori',
    'Rruga Partizani',
    'Rruga Gaqo Avrazi',
    'Rruga Koço Tupa',
    'Rruga e Drenoves',
    'Rruga Thanas Floqi',
    'Rruga Niko Dodona',
    'Rruga Kristaq Papagjiri',
    'Rruga Niko Kovaci',
    'Rruga Edit Durham',
  ],
  Elbasan: [
    'Rruga 11 Nëntori',
    'Rruga Kozma Naska',
    'Rruga Rinia',
    'Rruga 28 Nëntori',
    'Rruga Koco Brisku',
    'Rruga Vasil Kokoneshi',
    'Rruga e Re',
    'Rruga Kadri Gani',
    'Rruga Ismail Zyma',
    'Rruga Shpëtim Arapi',
    'Rruga Kostaq Cipo',
  ],
  Shkodër: [
    'Rruga Ibrahim Rugova',
    'Rruga Isuf Sokoli',
    'Rruga Ludovik Saraçi',
    'Rruga Vllazërit Frashëri',
    'Rruga Nazmi Kryeziu',
    'Rruga Marin Bicikemi',
    'Rruga 3 Heronjtë',
    'Rruga Lëvizja e Postribës',
    'Rruga Pogej',
    'Rruga Fahri Ramadani',
    'Rruga Dasho Shkreli',
  ],
  Kukës: [
    'Rruga Prizreni',
    'Rruga Dituria',
    'Rruga Deshmoret',
    'Rruga Kukesi i Ri',
    'Rruga Stadiumi',
    'Rruga Mahmut Daci',
    'Rruga Kosova',
    'Rruga Lidhja e Prizrenit',
    'Rruga Nene Tereza',
    'Rruga Clirimi',
    'Rruga 1 Qershori',
  ],
  Vlorë: [
    'Rruga Gjergj Kastrioti',
    'Rruga Mato Robi',
    'Rruga Cajupi',
    'Rruga Kosova',
    'Rruga Murat Tërbaçi',
    'Rruga Çamëria',
    'Rruga Piro Sava',
    'Rruga Mis Durhan',
    'Rruga Enver Jaho',
    'Rruga Sulejman Delvina',
    'Rruga Mustafa Bello',
  ],
  Berat: [
    'Rruga Antipatrea',
    'Rruga Staver Naco',
    'Rruga Shpiragu',
    'Rruga Gaqi Gjika',
    'Rruga Petrit Lulo',
    'Rruga e Teqesë',
    'Rruga Tafil Skëndo',
    'Rruga Shkembi',
    'Rruga Stiliano Bandilli',
    'Rruga Jani Kosta',
    'Rruga Kristaq Tutulani',
  ],
  Lezhë: [
    'Rruga Kuvendi i Arbërit',
    'Rruga Frang Bardhi',
    'Rruga Varosh',
    'Rruga Kosova',
    'Rruga Luigj Gurakuqi',
    'Rruga Franz Josef Strauss',
    'Rruga e Spitalit',
    'Rruga e Gurrave',
    'Rruga Hydajet Lezha',
    'Rruga Vëllezërit Coku',
    'Rruga e Portit',
  ],
  Gjirokastër: [
    'Rruga Doktor Vasil Jorgji',
    'Rruga Alqi Kondi',
    'Rruga Zeman Haska',
    'Rruga Zejtareve',
    'Rruga Gjin Zenebisi',
    'Rruga Jonuz Cuci',
    'Rruga Gjin Bue Shapata',
    'Rruga Evlia Celebi',
    'Rruga Astrit Karagjozi',
    'Rruga Partizani',
    'Rruga Vezirit',
  ],
  Fier: [
    'Rruga Jakov Xoxa',
    'Rruga Ramiz Aranitasi',
    'Rruga Jani Bakalli',
    'Rruga Andon Xoxa',
    'Rruga Naun Kacaku',
    'Rruga Hysni Toska',
    'Rruga e Semanit',
    'Rruga Thanas Ikonomi',
    'Rruga Harrilla Bozdo',
    'Rruga Kastriot Muço',
    'Rruga Janaq Kilica',
  ],
  Dibër: [
    'Rruga Abdyl Frashëri',
    'Rruga Nazmi Rushiti',
    'Rruga Suf Xhelili',
    'Rruga Jashar Kola',
    'Rruga Dali Ndreu',
    'Rruga Rahim Gjika',
    'Rruga Donika Kastrioti',
    'Rruga Nexhat Agolli',
    'Rruga Ahmet Kallaverja',
    'Rruga Sul Shehu',
    'Rruga Iljaz Pashe Dibra',
  ],
};
